apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  
  - name: PostgreSQL
    type: postgres
    url: postgresql:5432
    database: sensus_alerts
    user: sensus_user
    secureJsonData:
      password: sensus_password
    jsonData:
      sslmode: "disable"