apiVersion: v1
kind: Secret
metadata:
  name: enodai-secrets
  namespace: enodai
type: Opaque
stringData:
  POSTGRES_PASSWORD: "enod_password"
  GRAFANA_ADMIN_PASSWORD: "enod_password"
  JWT_SECRET_KEY: "change-this-in-production"
