apiVersion: v1
kind: Secret
metadata:
  name: sensusai-secrets
  namespace: sensusai
type: Opaque
stringData:
  POSTGRES_PASSWORD: "sensus_password"
  GRAFANA_ADMIN_PASSWORD: "sensus_password"
  JWT_SECRET_KEY: "change-this-in-production"
